[package]
name = "aoc19"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-rust = { path = "../aoc-rust" }
crossbeam = "0.7"
eyre = "0.6.9"
itertools = "0.8.2"
num = "0.2"
pathfinding = "2.0.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmarks"
harness = false