[workspace]
members = [
    "day03",
    "day04",
    "day05",
    "day06",
    "day07",
    "day08",
    "day09",
    "day10",
    "day11",
    "day12",
    "day13",
    "day14",
    "day15",
    "day16",
]

[workspace.package]
version = "0.1.0"
edition = "2021"