name: Github pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and deploy github pages
    runs-on: windows-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'v0.17.5'

      - name: Build webapp
        run: trunk build --release --no-default-features ./aoc-solver/index.html --dist ./docs --public-url "/AdventOfCode"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
